parameters:
  - name: dependsOn
    type: object
    default: ''

  - name: displayName
    type: string

  - name: subscription
    type: string
    
  - name: group
    type: string

  - name: environment
    type: string

jobs:
  - job: CreateStorage
    dependsOn:
      - ${{ if parameters.dependsOn }}:
          - ${{ parameters.dependsOn }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: AzureCLI@2
        displayName: add FW rule
        name: addFWrule
        inputs:
          azureSubscription: ${{ parameters.subscription }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            export ip=$(curl "http://ifconfig.me/ip")
            az storage account network-rule remove --account-name $(devopsStorageAccount) -g $(devopsResourceGroup) --ip-address $ip/32 
  
