parameters:
  - name: subscription
    type: string

  - name: group
    type: string

  - name: dependsOn
    type: object
    default: ''

  - name: displayName
    type: string

jobs:
  - job: Logger
    displayName: Logger
    steps:
      - bash: curl "http://ifconfig.me/ip"

  - job: TerraformPlan
    dependsOn:
      - ${{ if parameters.dependsOn }}:
          - ${{ parameters.dependsOn }}
    variables:
      - group: ${{ parameters.group }}
    displayName: ${{ parameters.displayName }}
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: ../steps/tf-install.yaml
      - template: ../steps/tf-init.yaml
        parameters:
          subscription: ${{ parameters.subscription }}
      - template: ../steps/tf-plan.yaml
        parameters:
          subscription: ${{ parameters.subscription }}
